#!/bin/bash -x

echo "User :    " $PAM_USER
echo "Type :    " $PAM_TYPE
echo "Service : " $PAM_SERVICE

if [ -z "${PAM_USER}" ]; then
	echo \"'$PAM_USER'\" not set
	exit 1
fi

if [ "${PAM_USER}" = "nobody" ]; then
	echo nobody omitted
	exit 0
fi

TMP_ROOT=/tmp
TMP_HOME=home
TMP_FOLDER=tmp
HOME=$(getent passwd "${PAM_USER}" | cut -d: -f6)

if [ "$PAM_TYPE" = "open_session" ]; then
	#make sure ${TMP_ROOT}/${TMP_HOME} exists
	if [ ! -d "${TMP_ROOT}/${TMP_HOME}" ]; then
		mkdir -p "${TMP_ROOT}/${TMP_HOME}"
	fi
	#touch services file and append service if not found
	if [ ! -f "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services" ];then
		touch "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services"
		#create new tmp folder in $TMP_ROOT and chown
		TEMP_DIR=$(mktemp -d "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.${TMP_FOLDER}.XXXXXX")
		chown "${PAM_USER}:${PAM_USER}" "${TEMP_DIR}"
		echo "created new $TMP_FOLDER folder"
		#relink tmp folder in $HOME
		if [ ! -L "${HOME}/${TMP_FOLDER}" ] || [ ! -e "${HOME}/${TMP_FOLDER}" ]; then
			[ -L "${HOME}/${TMP_FOLDER}" ] && unlink "${HOME}/${TMP_FOLDER}"
			ln -sf "${TEMP_DIR}" "${HOME}/${TMP_FOLDER}" 
			chown -h "${PAM_USER}:${PAM_USER}" "${HOME}/${TMP_FOLDER}"
			echo "relinked $TMP_FOLDER in $TMP_HOME"
		fi

	fi
	#add service to file
	if ! grep -q "${PAM_SERVICE}" "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services"; then
		echo "${PAM_SERVICE}" >> "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services"
		echo "added service ${PAM_SERVICE} to services file"
	fi

	echo "\"open_session\" successful for \"$PAM_USER\" from \"$PAM_SERVICE\""
	exit 0

elif [ "$PAM_TYPE" = "close_session" ]; then
	#remove current_service
	sed -i "/${PAM_SERVICE}/d" "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services"  
	#if services is empty, then remove old tmp folders
	if [ "0" -eq $(wc -l < "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services") ]; then
		find "${TMP_ROOT}/${TMP_HOME}" -maxdepth 1 -type d -iname "${PAM_USER}.${TMP_FOLDER}.*" -delete
		rm "${TMP_ROOT}/${TMP_HOME}/${PAM_USER}.services"
		unlink "${HOME}/${TMP_FOLDER}"
		echo removing all files for \"$PAM_USER\"
	fi

	echo "\"close_session\" successful for \"$PAM_USER\" from \"$PAM_SERVICE\"" 
	exit 0 
fi

